namespace Osiris.Application.Features.Dashboard.DTOs;

public sealed record MonthlyDashboardSummaryDto(
    int Year,
    int Month,
    OnboardingDto Onboarding,
    decimal IncomeTotal,
    decimal SpendingTotal,
    IReadOnlyCollection<SpendingByCategoryDto> SpendingByCategory,
    CashFlowSummaryDto CashFlow,
    IReadOnlyCollection<CreditCardDashboardDto> CreditCards,
    IReadOnlyCollection<UpcomingObligationDto> UpcomingObligations,
    IReadOnlyCollection<DashboardAlertDto> Alerts,
    decimal BillsDueInMonthTotal,
    int BillsDueInMonthCount,
    decimal BillsOpenInMonthTotal,
    decimal StatementsDueInMonthTotal,
    int StatementsDueInMonthCount,
    decimal StatementsOpenInMonthTotal,
    decimal TotalOpenStatementsBalance,
    decimal TotalOpenBillsBalance,
    decimal StatementPaymentsInMonthTotal,
    decimal FutureInstallmentsTotal,
    int OverdueStatementsCount,
    decimal OverdueStatementsBalance,
    int PartiallyPaidStatementsCount);
